services:
  db_corelab:
    image: postgres:16.3
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network_core_note
    restart: unless-stopped

  backend_corelab:
    build: .
    volumes:
      - .:/usr/src/corelab
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_corelab:5432/${POSTGRES_DB}"  
    ports:
      - "3333:3333"
    networks:
      - network_core_note
    restart: unless-stopped
    depends_on:
      - db_corelab
    entrypoint: ["/usr/src/corelab/init.sh"]

networks:
  network_core_note:

volumes:
  postgres_data:
